---
version: 1.0
gsf:
  basic:
    backend: gloo
    verbose: false
  gnn:
    model_encoder_type: rgcn
    fanout: "10, 10"
    num_layers: 2
    hidden_size: 128
    use_mini_batch_infer: true
    node_feat_name:
        - Address1:id_embeddings
        - Address2:id_embeddings
        - Card1:id_embeddings
        - Card2:id_embeddings
        - Card3:id_embeddings
        - Card4:id_embeddings
        - Card5:id_embeddings
        - Card6:id_embeddings
        - P_emaildomain:id_embeddings
        - ProductCD:id_embeddings
        - R_emaildomain:id_embeddings
        - Transaction:M1,M2,M3,M4,M5,M6,M7,M8,M9,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,TransactionAmt
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.
    lr: 0.001
    lm_tune_lr: 0.0001
    num_epochs: 30
    batch_size: 1024
    wd_l2norm: 0
    no_validation: false
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    target_ntype: "Transaction"
    label_field: "isFraud:Int"
    multilabel: false
    num_classes: 2